name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
              distribution: 'microsoft'
              java-version: '17'
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install
          run: npm install

        - name: Test
          run: clear-qa-report
          run: pipeline-qa
          run: generate-qa-report
        - uses: actions/download-artifact@v3.0.0
          if: failure()
          with:
            name: logs
            path: logs
