name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
              distribution: 'microsoft' # See 'Supported distributions' for available options
              java-version: '17'
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 18

        - name: Install
          run: npm install

        - name: Test
          run: npm run wdio ./user/qa/qa.conf.js --spec ./test/specs/homePage.js

        - uses: actions/download-artifact@v3.0.0
          if: failure()
          with:
            name: logs
            path: logs
