name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
              distribution: 'microsoft'
              java-version: '17'
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install
          run: npm install

        - name: Clear report
          run: npm run clear-qa-report

        - name: Test
          run: npm run pipeline-qa

        - name: Generate report
          run: npm run generate-qa-report
        - name: Allure report
          uses: afiore/action-allure-report@v0.1.0

          
        - uses: actions/download-artifact@v3.0.0
          if: failure()
          with:
            name: logs
            path: logs
